delete from store_returns where sr_returned_date_sk in (select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
delete from store_sales where ss_sold_date_sk in (select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
delete from catalog_returns where cr_returned_date_sk in(select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
delete from catalog_sales where cs_sold_date_sk in (select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
delete from web_returns where wr_returned_date_sk in (select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
delete from web_sales where ws_sold_date_sk in (select d_date_sk from date_dim where d_date between '${date1}' and '${date2}')
