USE ${TPCDS_DBNAME};

insert overwrite table call_center select * from call_center_text;
insert overwrite table catalog_page select * from catalog_page_text;
insert overwrite table catalog_returns select * from catalog_returns_text;
insert overwrite table catalog_sales select * from catalog_sales_text;
insert overwrite table customer select * from customer_text;
insert overwrite table customer_address select * from customer_address_text;
insert overwrite table customer_demographics select * from customer_demographics_text;
insert overwrite table date_dim select * from date_dim_text;
insert overwrite table household_demographics select * from household_demographics_text;
insert overwrite table income_band select * from income_band_text;
insert overwrite table inventory select * from inventory_text;
insert overwrite table item select * from item_text;
insert overwrite table promotion select * from promotion_text;
insert overwrite table reason select * from reason_text;
insert overwrite table ship_mode select * from ship_mode_text;
insert overwrite table store select * from store_text;
insert overwrite table store_returns select * from store_returns_text;
insert overwrite table store_sales select * from store_sales_text;
insert overwrite table time_dim select * from time_dim_text;
insert overwrite table warehouse select * from warehouse_text;
insert overwrite table web_page select * from web_page_text;
insert overwrite table web_returns select * from web_returns_text;
insert overwrite table web_sales select * from web_sales_text;
insert overwrite table web_site select * from web_site_text;
