USE ${TPCDS_DBNAME};

insert table call_center select * from call_center_text;
insert table catalog_page select * from catalog_page_text;
insert table catalog_returns select * from catalog_returns_text;
insert table catalog_sales select * from catalog_sales_text;
insert table customer select * from customer_text;
insert table customer_address select * from customer_address_text;
insert table customer_demographics select * from customer_demographics_text;
insert table date_dim select * from date_dim_text;
insert table household_demographics select * from household_demographics_text;
insert table income_band select * from income_band_text;
insert table inventory select * from inventory_text;
insert table item select * from item_text;
insert table promotion select * from promotion_text;
insert table reason select * from reason_text;
insert table ship_mode select * from ship_mode_text;
insert table store select * from store_text;
insert table store_returns select * from store_returns_text;
insert table store_sales select * from store_sales_text;
insert table time_dim select * from time_dim_text;
insert table warehouse select * from warehouse_text;
insert table web_page select * from web_page_text;
insert table web_returns select * from web_returns_text;
insert table web_sales select * from web_sales_text;
insert table web_site select * from web_site_text;
