USE ${TPCDS_DBNAME};

DROP TABLE call_center_text;
DROP TABLE catalog_page_text;
DROP TABLE catalog_returns_text;
DROP TABLE catalog_sales_text;
DROP TABLE customer_text;
DROP TABLE customer_address_text;
DROP TABLE customer_demographics_text;
DROP TABLE date_dim_text;
DROP TABLE household_demographics_text;
DROP TABLE income_band_text;
DROP TABLE inventory_text;
DROP TABLE item_text;
DROP TABLE promotion_text;
DROP TABLE reason_text;
DROP TABLE ship_mode_text;
DROP TABLE store_text;
DROP TABLE store_returns_text;
DROP TABLE store_sales_text;
DROP TABLE time_dim_text;
DROP TABLE warehouse_text;
DROP TABLE web_page_text;
DROP TABLE web_returns_text;
DROP TABLE web_sales_text;
DROP TABLE web_site_text;
